COLUMNS:
  customerid:          object
  gender:               object
  seniorcitizen:         int64
  partner:              object
  dependents:           object
  tenure:                int64
  phoneservice:         object
  multiplelines:        object
  internetservice:      object
  onlinesecurity:       object
  onlinebackup:         object
  deviceprotection:     object
  techsupport:          object
  streamingtv:          object
  streamingmovies:      object
  contract:             object
  paperlessbilling:     object
  paymentmethod:        object
  monthlycharges:      float64
  totalcharges:         object
  churn:                object

TARGET_COLUMN:
  name: churn